---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    name: postgres-service
    author: chi
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgres-pod
    author: chi
...